name: mementar library CI

on: [push]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04]
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: mkdir build && cd build
    - name: configure
      run: cmake ..
    - name: build
      run: cmake --build .
